[package]
name = "serenity-rust"
version = "0.1.0"
edition = "2021"
links = "lagom-core"

[dependencies]
cxx = "1.0"

[lib]
crate-type=["staticlib", "rlib"]

[build-dependencies]
cxx-build = "1.0"
cmake = "0.1"
